INSERT INTO usuario
(nombre, apellido, email, password, telefono, documento, activo, role)
VALUES
    ('juan jose', 'sierra ortega', 'juan@gmail.com',
     '$2a$10$JWhqh1.PEOuBd0PUjEPTB..LgNfCGQcFZaeL17tNhpHftAqq3VzGS',
     '1234567880','1112223344',true,'USER');

INSERT INTO evento (
    id_usuario,
    nombre,
    descripcion,
    categoria,
    lugar,
    ciudad,
    direccion,
    fecha_evento,
    fecha_creacion,
    capacidad,
    precio_base,
    estado
)
VALUES
    (
        (SELECT id FROM usuario WHERE email = 'juan@gmail.com'),
        'Afterlife Bogotá 2026',
        'Festival de música electrónica con artistas internacionales de techno melódico.',
        'CONCIERTO',
        'Parque Simón Bolívar',
        'Bogotá',
        'Av. Calle 63 #68-95',
        '2026-08-15 18:00:00',
        NOW(),
        18000,
        350000,
        'ACTIVO'
    ),
    (   (SELECT id FROM usuario WHERE email = 'juan@gmail.com'),
        'Resistance Medellín',
        'Evento de techno underground con DJs internacionales.',
        'CONCIERTO',
        'Plaza Mayor',
        'Medellín',
        'Calle 41 #55-80',
        '2026-09-12 20:00:00',
        NOW(),
        12000,
        280000,
        'ACTIVO'
    ),
    (
        (SELECT id FROM usuario WHERE email = 'juan@gmail.com'),
        'Tomorrowland Unite Colombia',
        'Experiencia inspirada en el famoso festival belga de música electrónica.',
        'CONCIERTO',
        'Centro de Eventos Valle del Pacífico',
        'Cali',
        'Yumbo',
        '2026-11-07 16:00:00',
        NOW(),
        25000,
        450000,
        'ACTIVO'
    ),
    (
        (SELECT id FROM usuario WHERE email = 'juan@gmail.com'),
        'Techno Warehouse Session',
        'Noche de techno industrial en una locación tipo warehouse.',
        'CONCIERTO',
        'Distrito Industrial',
        'Bogotá',
        'Zona Industrial Fontibón',
        '2026-07-18 22:00:00',
        NOW(),
        3500,
        180000,
        'ACTIVO'
    ),
    (
        (SELECT id FROM usuario WHERE email = 'juan@gmail.com'),
        'Black Coffee Live',
        'Presentación especial del reconocido DJ sudafricano Black Coffee.',
        'CONCIERTO',
        'Movistar Arena',
        'Bogotá',
        'Diagonal 61C #26-35',
        '2026-10-03 20:00:00',
        NOW(),
        14000,
        320000,
        'ACTIVO'
    ),
    (
        (SELECT id FROM usuario WHERE email = 'juan@gmail.com'),
        'Carl Cox Revolution',
        'Show de techno y house con uno de los DJs más influyentes del mundo.',
        'CONCIERTO',
        'Centro de Convenciones',
        'Cartagena',
        'Getsemaní',
        '2026-12-05 21:00:00',
        NOW(),
        10000,
        390000,
        'ACTIVO'
    ),
    (
        (SELECT id FROM usuario WHERE email = 'juan@gmail.com'),
        'Boiler Room Bogotá',
        'Experiencia inmersiva de música electrónica con artistas locales e internacionales.',
        'CONCIERTO',
        'Corferias',
        'Bogotá',
        'Carrera 37 #24-67',
        '2026-06-20 19:00:00',
        NOW(),
        7000,
        220000,
        'ACTIVO'
    ),
    (
        (SELECT id FROM usuario WHERE email = 'juan@gmail.com'),
        'Medellín Electronic Festival',
        'Festival de techno, house y melodic techno con múltiples escenarios.',
        'CONCIERTO',
        'Parque Norte',
        'Medellín',
        'Cra. 53 #76-115',
        '2026-08-29 15:00:00',
        NOW(),
        16000,
        260000,
        'ACTIVO'
    ),
    (
        (SELECT id FROM usuario WHERE email = 'juan@gmail.com'),
        'Underground Techno Night',
        'Sesión nocturna enfocada en techno oscuro y minimal.',
        'CONCIERTO',
        'Club Industrial',
        'Barranquilla',
        'Cra. 51B #79-97',
        '2026-09-26 23:00:00',
        NOW(),
        2500,
        150000,
        'ACTIVO'
    ),
    (
        (SELECT id FROM usuario WHERE email = 'juan@gmail.com'),
        'Adriatique Experience',
        'Evento exclusivo con el dúo suizo Adriatique y artistas invitados.',
        'CONCIERTO',
        'Centro de Eventos Autopista Norte',
        'Bogotá',
        'Autopista Norte Km 19',
        '2026-11-21 18:00:00',
        NOW(),
        9000,
        340000,
        'ACTIVO'
    );

